export const DAILY_RETAILER_CONFIG_ALARM = 'DAILY_RETAILER_CONFIG_ALARM'
export const RETRY_CONFIG_FETCH_ALARM = 'RETRY_CONFIG_FETCH_ALARM'

export const RATE_LIMIT_ALARM = 'RATE_LIMIT_ALARM'

export const SERVICE_UNAVAILABLE_ALARM = 'SERVICE_UNAVAILABLE_ALARM'

export const ANALYTICS_BATCH_ALARM = 'ANALYTICS_BATCH_ALARM'
